### ISSUE TITLE
Group land classes before counting?

### ISSUE THREAD

**Issue by swd-turner** [IMMM-SFA/teleconnect#12]
Item 2 on the teleconnections matrix is to count # of LULC types in each watershed. Currently we're reading all separate categories of NLCD land classes as different types. It might be sensible to group these in some way before counting, or filter to count only certain types of land category. For example, NLCD has category `21 Developed Medium Intensity` and category `22 Developed High Intensity`. Presumably we don't want two separate counts if both are present in a watershed .

Opening this issue here for discussion. A similar discussion may be needed for the crop types.

**Comment by crvernon** [comment]
@swd-turner I agree about the preclassification.  This maybe something for the new hire to take on because we will need to see where these categories make sense to dissolve without loosing too much detail.

**Comment by cdburley** [comment]
@swd-turner and @crvernon - I too agree with the pre-classification/grouping. As commonly used as these land classes are you would think that there is a standardized way to reduce the number of classes. Maybe we should reach out to Maoyi and/or Kate Calvin to get their input?

**Comment by swd-turner** [comment]
So [here](https://www.mrlc.gov/data/legends/national-land-cover-database-2011-nlcd2011-legend) are the classes we're dealing with. Some possible options rather than counting number of types:

- % land area in watershed cultivated or developed at medium to high intensity
- A binary variable indicating whether the watershed is "protected" (i.e., no or very little cultivation and or development... say, less than 5% cultivation and less than 5% of any development).
- Count based three classes: developed, cultivated, natural.

**Comment by KristianNelson** [comment]
This might be over complicating the issue just a bit, but I thought I would share my thoughts on analyzing the land types within the watersheds.

Looking at the % of a land type area or the number of types doesn't say much about how they affect the watershed. It's important to not only understand the composition of the land types within the watershed, but also the configuration and connectivity of them. A high % of vegetated areas could be beneficial if those vegetated areas are connected and configured in a way that mitigates runoff from outer developed areas. At the same time, a high % of vegetated areas might not be helpful if that large % is just made up of small patches of vegetation dispersed randomly throughout the watershed. 

I think focusing on development/cultivation and simplifying it down to if the watershed is protected from disturbance or not(with the binary variable) is a good idea. It doesn't need to consider the configuration of the land types and is just a matter of whether there is unrestricted development and cultivation within the watershed or not. 

Let me know what you think!

**Comment by swd-turner** [comment]
@KristianNelson could you please reflect on this and propose a scheme for categorizing a city's watersheds according to landclasses? (i.e., three or four categories to reflect varying degrees of land protection in each city's water supply lands, "unprotected", "managed", "fully protected" for example... how could we assign a given catchment to those classes using NLCD data?).

**Comment by KristianNelson** [comment]
I think a better way we can characterize the watersheds is to rank them based on levels of development/cultivation. If you rank them based on the amount of those classes, it can at least give a picture of how much the functionality of the watershed is being impacted. 

I don't think we have enough information from just the NLCD data to determine levels of protection since there are many factors that play into how a watershed is protected. Maybe a logarithmic scale of development/cultivation with rankings 1-5? Could look something like this (can be adjusted): 
1 = 0-2% 
2 = 2.1-10%
3 = 10.1-30%
4 = 30.1-60%
5 = 60.1-100%
Let me know what you think.

**Comment by swd-turner** [comment]
@KristianNelson would *any* of our catchments fall into categories 3, 4, or 5??

**Comment by KristianNelson** [comment]
@swd-turner I think Salt Lake City's watershed had pretty high development, but again that scale can be adjusted around what the mean % is. Say our highest % is 30, then it can look something like:
1 = 0-1%
2 = 1.1-5%
3 = 5.1-15%
4 = 15.1-30%
5 = 30.1-100%

**Comment by swd-turner** [comment]
0 - 1; 1 - 5; and 5+ seems reasonable, but we should inform this decision by looking at the actual data. What are the actual % values of development/cultivation across the 235 cities?

**Comment by KristianNelson** [comment]
@swd-turner For development and cultivation % combined, here are some examples:

Charlotte, NC - 21.9%
New York, NY - 12%
Baltimore, MD - 24.9%
Boston, MA - 10.9 %
Dallas, TX - 32.9%
Portland, OR - 0.5%
Seattle, WA - 5.8%
San Francisco, CA - 1.8%
Los Angeles, CA - 1.75%

**Comment by swd-turner** [comment]
@KristianNelson Cool--interesting numbers there. I hadn't anticipated it would be so high and I'm surprised Seattle is > 5%. Given these numbers, I think the five categories you suggest above look good... Can you please go ahead and implement this in the package? So instead of the n_landclasses variable, it will be landclass_category. Please incorporate some suitable labeling for these categories, too (as opposed to just numbers 1 to 5)... could be something like "pristine" for < 0.5% to "heavily developed" for > 30 %.

**Comment by swd-turner** [comment]
@KristianNelson what categories are you counting as "developed/cultivated" ? I just had a look at Austin and it looks to be > 50% shrub, so I'm not sure how it can be 69% developed/cultivated...

**Comment by KristianNelson** [comment]
Yea I knew that looked off, I am looking into it now.
