### ISSUE TITLE
Add count: # irrigation districts dependent on city watersheds

### ISSUE THREAD

**Issue by swd-turner** [IMMM-SFA/teleconnect#22]

**Comment by KristianNelson** [comment]
I found a shapefile for irrigation areas here:
http://www.fao.org/nr/water/aquastat/irrigationmap/index10.stm

Let me know if this is useful in anyway. Other than that I haven't had much luck finding district data.

**Comment by swd-turner** [comment]
Excellent. This could be really useful. Please go ahead and investigate further--if you think the data are suitable for this or #25 then press ahead and implement in the package. You can describe the data to the group during the next conference call.

**Comment by swd-turner** [comment]
Abandoning this for now due to lack of available data.
