### ISSUE TITLE
Add count: # economic land classes

### ISSUE THREAD

**Issue by swd-turner** [IMMM-SFA/teleconnect#46]
Data [here](https://journals.plos.org/plosone/article?id=10.1371/journal).

**Comment by KristianNelson** [comment]
@swd-turner link is either broken or doesn't exist anymore. Says "page not found".

**Comment by swd-turner** [comment]
[try this](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0094628)

**Comment by KristianNelson** [comment]
Has it been decided what we are considering "economic" land classes to be? Are all of the classes from the paper considered economic or do some need to be taken out?

**Comment by swd-turner** [comment]
@KristianNelson perhaps provide a list of the classes and open the discussion @cdburley and @crvernon. I think Jennie mentioned 75 economic classes, including golf courses etc (?)... we might want to group these into a smaller number of categories. Please propose a strategy for doing this.
