### ISSUE TITLE
Add count: # crops traded nationally vs internationally

### ISSUE THREAD

**Issue by swd-turner** [IMMM-SFA/teleconnect#48]
Task 3 on the original planning document. See FAOSTAT_data_8-13-2019.csv

**Comment by KristianNelson** [comment]
@swd-turner Just double checking, the OG planning document says "Count # of nationally and globally-traded crops in each catchment". I don't see any variables related to nationally/internationally traded crops in that CSV file that would let me differentiate national and international crops.

**Comment by swd-turner** [comment]
Yup we'll need to think about how to approach this one with the available information. Let's revisit this Monday.

**Comment by swd-turner** [comment]
No obvious way to resolve this issue. Closing for now.
